INSERT INTO SUPERHEROS (NAME) VALUES ('Spiderman');
INSERT INTO SUPERHEROS (NAME) VALUES ('Batman');
INSERT INTO SUPERHEROS (NAME) VALUES ('Ironman');
INSERT INTO SUPERHEROS (NAME) VALUES ('Thor');
INSERT INTO SUPERHEROS (NAME) VALUES ('Cat Woman');
INSERT INTO SUPERHEROS (NAME) VALUES ('Superman');
INSERT INTO SUPERHEROS (NAME) VALUES ('Capitan America');
INSERT INTO SUPERHEROS (NAME) VALUES ('Hulk');
INSERT INTO SUPERHEROS (NAME) VALUES ('Bruja Escarlata');
